# Generated by Django 5.0.14 on 2025-06-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_ingredient_quantity_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_items",
                to="menu.menuitem",
            ),
        ),
    ]
