# Generated by Django 5.0.14 on 2025-06-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_recipeitem_menu_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="cost",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
